apiVersion: apps/v1
kind: Deployment
metadata:
  name: emi-calculator
  namespace: storagetax
  labels:
    app: emi-calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emi-calculator
  template:
    metadata:
      labels:
        app: emi-calculator
    spec:
      containers:
        - name: emi-calculator
          image: acrstoragetaxnonprod.azurecr.io/emi-calculator:v1
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 20
