name: Deploy UAMI Module

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-uami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy uami module
        run: |
          az deployment group create \
            --resource-group rg-storagetax-nonprod \
            --template-file platform/modules/uami/main.bicep \
            --parameters platform/modules/uami/parameters/nonprod-base.bicepparam